- name: Preparando ambiente...
  hosts: all
  become: true

  tasks:
    - name: Atualizando dependencias.
      command: npm i xhr2
      
    - name: Executando script-js
      #      command: node script-umock.js
      command: node /root/magico/script-umock.js
