- name: Send Notification  
  hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Sending an email
    community.general.mail:
      host: umail.usto.re
      port: 587
      username: noreply@ucloud.usto.re
      password: BHU*nji9
      to: 
      - lucas.tavora@usto.re
      subject: Nova compra realizada - {{PRODUCT_NAME}}
      body: Prezado {{NAME}}, o Sr comprou o {{PRODUCT_NAME}} que custa {{PRICE_VALUE}} Atenciosamente, Equipe CLARO
