- name: Listando software instalados
  hosts: all
  become: true
  tasks:
  - name: Gather the package facts
    ansible.builtin.package_facts:
      manager: auto

  - name: Get package facts
    set_fact:
      packages: "{{ ansible_facts.packages }}"

  - name: Print the package facts
    ansible.builtin.debug:
      msg: "{{ packages.keys() }}"

