- name: "Playing with Ansible and Git"
  hosts: localhost
  vars:
     ansible_python_interpreter: /usr/bin/python3
  collections:
     - azure.azcollection
  tasks:
  - name: "Create/Update Azure Recovery Service vault"
    azure_rm_recoveryservicesvault:
    resource_group: 'azurebkp'
    name: 'vaultteste01'
    location: 'brazilsouth'
    state: 'present'

