---
- name: Run tasks for dump mode
  include_tasks:
    file: "dump.yml"
  when: dump_mode|bool == true

- name: Run tasks for restore mode
  include_tasks:
    file: "restore.yml"
  when: restore_mode|bool == true
